### ISSUE TITLE
AuthenticationError when trying to re-create a user

### ISSUE THREAD

**Issue by dkarter** [synapsepayments/synapse_pay-ruby#1]
**_Steps:**_
1. Create a user using the following call:
   
   ``` ruby
   SynapsePay::User.create(email: 'test@example.com', fullname: 'test me', ip_address: '11.111.11.11', phonenumber: '123456789')
   ```
2. Try to create the user again with above code

**Expected:**
Email already registered error message as in API (better yet - have the api return the oauth token)

**Actual:**

```
SynapsePay::AuthenticationError: Authentication failed. Please check your API key and verify that it is correct.
```

Screenshots
From gem:
![](https://www.dropbox.com/s/g7vxg98trs2bnfr/Screenshot%202015-05-14%2015.15.24.png?dl=1)

When hitting API directly:
![](https://www.dropbox.com/s/fb8ixy83akcfuj2/Screenshot%202015-05-14%2015.18.49.png?dl=1)

**Comment by sankaet** [comment]
Dorian--- please try this

```
client = SynapsePay::User.create({
  :email => "test-user@synapsepay.com",
  :fullname => "Test Account",
  :ip_address => "11.111.11.11",
  :phonenumber => "123456789"
  :force_create => "no"
})

```

I 100% agree we need to show correct messages coming from the server

**Comment by joncalhoun** [comment]
@sankaet The reason this is throwing an Authentication error is because the server is returning a 401 status code when a user already exists, which likely isn't the best status code for this situation.

@dkarter You should be able to access the json response with _any_ error in the ruby library by calling `error.json`, so in this example you could call `error.json.reason` to see the message you mentioned, and I will update the code to make the error clearer.

**Comment by joncalhoun** [comment]
I updated the samples to include a `:force_create => "no"` example, and updated the error to show a more useful message. You should now see something like:

```
SynapsePay::AuthenticationError: (Status 401) {"reason": "Email already registered.", "success": false}
```

I also cleaned up our errors to make the response easier to access. You should be able to now do something like:

``` ruby
begin
  # This creates an oauth client for the newly created user.
  client = SynapsePay::User.create({
    :email => "test-user@synapsepay.com",
    :fullname => "Test Account",
    :ip_address => "11.111.11.11",
    :phonenumber => "123456789"
  })
rescue SynapsePay::APIError => e
  # Authentication Error inherits from APIError, so they both will be caught here
  puts e.json.response
end
```

This will get pushed to rubygems tonight.
