### ISSUE TITLE
Bank query: ArgumentError (wrong number of arguments (3 for 0..2)) 

### ISSUE THREAD

**Issue by fertobar** [synapsepayments/synapse_pay-ruby#12]
Hi, 
after login successfully when I want to retrieve my banks accounts via:
banks = client.banks.all
or
banks = client.banks.all(id: 123) #where is exist
I'm getting:
ArgumentError (wrong number of arguments (3 for 0..2))

Any idea for try to fix?

thanks

**Comment by fertobar** [comment]
I could found and the Issue.
Was because I already have a Bank class in my app, and in class APIList < APIResource, line:
instance_variable_set("@#{k}", v.map{ |i| @klass.new(i, @api_method, @client) })
try to create a Bank class. The point is that was taking my original Bank class, rather that the SynapsePay::Bank class

**Comment by joncalhoun** [comment]
We actually just found this bug today internally and will be pushing a fix shortly, but thanks for pointing it out :smile:

**Comment by fertobar** [comment]
thanks for the feedback @joncalhoun !
