### ISSUE TITLE
User.create only returns the OAuth token?

### ISSUE THREAD

**Issue by hrrf** [synapsepayments/synapse_pay-ruby#13]
In documentation:

> When you send the user/create payload, a user is created and we'll send you username, oauth_consumer_key, refresh_token and expires_in.

I'm only getting this when making calls to sandbox, where **key** represents my oauth key.

```
#<SynapsePay::Client:0x411ecf8> Headers: {
}, Params: {
  "oauth_consumer_key": "<key>"
}
```

**Comment by joncalhoun** [comment]
The rest of the attributes are there, but aren't printed out when `client.inspect` is called (which is the method that defines what is printed to a REPL).

If you check here: https://github.com/synapsepayments/synapse_pay-ruby/blob/master/lib/synapse_pay/client.rb#L3 you can see all the attributes defined and set. You should have no problem doing this:

``` ruby
c = SynapsePay::User.create(...)
c.username
c.user_id
```

and on the off chance there is new data added to the API before the lib is updated, you can do this:

``` ruby
c = SynapsePay::User.create(...)
c.json # this will be a hash of the json response from the server
```

That help?
