### ISSUE TITLE
`invalid_grant` when creating an order in sandbox

### ISSUE THREAD

**Issue by hrrf** [synapsepayments/synapse_pay-ruby#14]
I'm trying to create a realistic scenario to see if SynapsePay can solve our problem.  I need to let a **Company** pay an **Employee**.

I'm creating what I consider a **Company** entity by doing:

```
company = SynapsePay::User.create({
        :email => user_params[:email],
        :fullname => user_params[:fullname],
        :ip_address => my_first_public_ipv4,
        :phonenumber => user_params[:phonenumber],
        :force_create => "yes"
      })
```

This returns a `SynapsePay::User` with attributes as i'd expect, most notably the `:oauth_consumer_key`, `:refresh_token`, and `:user_id`.

Next, for simplicity I'm linking a non-MFA test bank using the `:oauth_consumer_key` and `:refresh_token` I just obtained from the above `SynapsePay::User.create`:

```
    client = SynapsePay::Client.new(oauth, refresh_token)
    client.refresh_access

    bank_params = {
      :username => 'synapse_nomfa',
      :password => 'test1234',
      :bank => 'Bank of America'
    }

    client.banks.link(bank_params)
```

My **Company** now has a linked bank.

OK:  now I **repeat** the entire process for what I consider an **Employee**.  I call `SynapseClient::User.create`, save the OAuth credentials, and then link an account in the exact same manner using the **Employee** OAuth.

At this point I theoretically have a **Company** and **Employee** user set up in SynapsePay, right?

Now I want to test creating an **Order** to represent a payment going **from** the **Company** to the **Employee**:

```
      # Create client from Company POV
      client = SynapsePay::Client.new(company_oauth, company_refresh_token)
      client.refresh_access

      client.orders.create({
        :amount => amount,
        :seller_id => employee_id,    # The employee.user_id
        :bank_id => company_bank_id   # The company bank id from linking
        })
```

Does that make sense?  

I can create the users.  I can link the banks.  When I go to instantiate the client for creating the **Order** as seen above, I can't seem to get anything but:

```
SynapsePay::AuthenticationError:
       {"reason": "invalid_grant", "success": false}
```

**Comment by joncalhoun** [comment]
It sounds like you are using an invalid refresh token. 

When you call `refresh_access` the first time for the company do you update the refresh token you are using for subsequent calls?

**Comment by joncalhoun** [comment]
Hi @hrrf I am going to close this since it has sat idle for a while. Let me know if you need it reopened.
