### ISSUE TITLE
Add expires_at date field to Client object

### ISSUE THREAD

**Issue by javierjulio** [synapsepayments/synapse_pay-ruby#15]
The JSON API now returns the date (UNIX timestamp) the auth expires, not just the amount of seconds it will expire in. For example, here is a hash of what comes back as the JSON result in Sandbox:

``` ruby
{
  :expires_at=>"1463692879", 
  :expires_in=>"30510765", 
  # ...
}
```

@sankaet could you please update the API docs to include this in the response samples? Also it should be up for discussion that now `refresh_access` only works once a token has expired whereas before it would regenerate new tokens anytime it was called, to make a note in the Samples document and maybe provide a flag to indicate if it changed? As it stands the request always completes successfully. Further, what error is generated if tokens expire? To verify, is it a 401 (AuthenticationError class)?

**Comment by joncalhoun** [comment]
Fully fixed in `0.0.7`

**Comment by joncalhoun** [comment]
@javierjulio can you move your 2nd question to another issue? Would make managing the issues easier if they are broken up :smile:

**Comment by javierjulio** [comment]
@joncalhoun no need to worry about the other question as they are working on that. Thanks for the update! Going to integrate this now.
