### ISSUE TITLE
v3 timeline

### ISSUE THREAD

**Issue by daryllxd** [synapsepayments/synapse_pay-ruby#18]
Hello all, I was wondering when the official gem would support version 3 of the SynapsePayments API? synapsepay.readme.io/v3.0/docs

**Comment by miguelperez** [comment]
+1.

**Comment by synapsepayuser** [comment]
@daryllxd @miguelperez We should be announcing something in next couple of days for this

**Comment by sankaet** [comment]
@daryllxd @miguelperez here is the new lib https://github.com/synapsepay/SynapsePayRest-Ruby

**Comment by miguelperez** [comment]
thanks.
