### ISSUE TITLE
How do I log in without username and password?

### ISSUE THREAD

**Issue by dkarter** [synapsepayments/synapse_pay-ruby#2]
After creating a user (which btw does not require a username and password) the next step to do anything appears to be logging in with a username and password.

quoting the samples.md file

> ## Create a user
> 
> ``` ruby
> # Make sure we are in Sandbox
> SynapsePay.api_base = SynapsePay.api_sandbox
> 
> SynapsePay.client_id = "client-id"
> SynapsePay.client_secret = "client-secret"
> 
> # This creates an oauth client for the newly created user.
> client = SynapsePay::User.create({
>   :email => "test-user@synapsepay.com",
>   :fullname => "Test Account",
>   :ip_address => "11.111.11.11",
>   :phonenumber => "123456789"
> })
> ```
> ## Login as a user
> 
> ``` ruby
> # Make sure we are in Sandbox
> SynapsePay.api_base = SynapsePay.api_sandbox
> 
> SynapsePay.client_id = "client-id"
> SynapsePay.client_secret = "client-secret"
> 
> # Returns an oauth client for this user
> client = SynapsePay::User.login("username", "password")
> ```

So how does one log in as a user with the oauthtoken returned by the first `create` call?

**Comment by dkarter** [comment]
Ideally if I have the oauth token I probably shouldn't even need to log in or have a method to login with the token. But not sure how I would add a card to a user without logging in because in the examples it seems to be done on the client (logged in user)

![](https://www.dropbox.com/s/5uzzwrvb2v7245s/Screenshot%202015-05-14%2017.45.44.png?dl=1)

**Comment by sankaet** [comment]
Dorian, this seems to be an issue. We are going to do a rigorous code review this weekend.

I would suggest do this:

```
client = SynapsePay::User.create({
  :email => "test-user@synapsepay.com",
  :fullname => "Test Account",
  :ip_address => "11.111.11.11",
  :phonenumber => "123456789"
  :force_create => "no"
})
```

This would return the existing customer if available without the login protocol. In the meantime we will work on adding support for oauth token client initialization as well

**Comment by joncalhoun** [comment]
@dkarter There are a few options.
- Like @sankaet said, you can use :force_create => "no" and this will return the user info for an existing user.
- You can use a refresh token to get a new client. eg:

``` ruby
client = SynapsePay::Client.refresh_access("refresh-token")
```
- You can just create a new client with the user's oauth token:

``` ruby
client = SynapsePay::Client.new("oauth-token", "refresh-token") 

# the refresh is optional, but if you provide it you can do this to refresh if your token expires:
client.refresh_access
```

This isn't shown clearly in the docs, so I will update the samples today.

**Comment by joncalhoun** [comment]
Also, you can always access the refresh_token and oauth_consumer_key in a client from a newly created user via:

``` ruby
client = SynapsePay::User.create(...)
client.oauth_consumer_key
client.refresh_token
```
