### ISSUE TITLE
Retrieving an added bank fails

### ISSUE THREAD

**Issue by javierjulio** [synapsepayments/synapse_pay-ruby#5]
If I successfully add a bank account:

``` ruby
client = SynapsePay::User.create({
  :email => "jonsmith@example.com",
  :fullname => "Jon Smith",
  :ip_address => "11.111.11.11",
  :phonenumber => "123456789",
  :force_create => "no"
})

bank = client.banks.add({
  :fullname => "Jon Smith",
  :account_num => "1111111111",
  :routing_num => "121000358",
  :nickname => "Example bank account",
  :account_type => "1",
  :account_class => "1"
})
```

I'll get a successful response with the bank info set. The problem is that loading that bank account info by id fails stating that the account does not exist:

``` ruby
#<SynapsePay::Bank:0x3fec729dc918 id=3046> Attributes: {
  "account_class": 1,
  "account_number_string": "******1111",
  "account_type": 1,
  "bank_name": null,
  "date": "2015-05-18T20:31:13.256665",
  "id": 3046,
  "is_active": null,
  "is_buyer_default": true,
  "is_seller_default": false,
  "is_verified": null,
  "name_on_account": "Jon Smith",
  "nickname": "Example bank account",
  "resource_uri": null,
  "routing_number_string": "*******58"
}
client.banks.retrieve('3046')
```

That last line on retrieving the bank by id fails with the following error message returned:

``````
SynapsePay::APIError: (Status 400) {"message": "Bank not found", "success": false, "title": "Bank not found"}```
``````

**Comment by joncalhoun** [comment]
Are you running this in sandbox or in production? I am not entirely sure why you are getting this error but we def need to look into it.

**Comment by sankaet** [comment]
javierjulio -- would you be able to send me the oauth_customer_key as a PM? you can also email it to me at sankaet@synapsepay.com

**Comment by javierjulio** [comment]
Yes definitely in sandbox mode. Running this all through the console with the gem cloned locally. I needed to so that I could debug the other issue reported as it was a showstopper for me. Happens for me consistently whether installed through ruby gems (v0.0.1) or from master branch.

**Comment by sankaet** [comment]
Jon, the problem seems to be that banks.retrive is pining /bank/refresh not bank/show

bank/refresh is used to refresh bank information like balance, address, email, etc. for a given bank.

bank/show is used to show all of the linked banks and if id is supplied, it even reveals individual accounts

**Comment by sankaet** [comment]
I have also updated the error message on the server for these kinds of cases

`{ 'success': False,'title':'Bank cannot refreshed','message':'Bank account cannot be refreshed since the account was not added using online banking' }`

**Comment by javierjulio** [comment]
@sankaet I knew something was odd about it hitting the /bank/refresh resource. Should have mentioned that. I'll message you the consumer key now. I was a little confused how to get that user info through the API but I realize now when searching for users, the login portion is to login as the merchant account and then I'm able to find the users I've added.

**Comment by joncalhoun** [comment]
@sankaet Thanks. I'll get the libs updated to reflect this.

**Comment by javierjulio** [comment]
@joncalhoun in the current state it doesn't seem to include `balance` field by the way. Would be great and very useful to get that through the Ruby lib. There seems to be some other fields missing too that aren't set on the Bank object when retrieved (currently loading all banks and getting the first one until this is resolved).

**Comment by joncalhoun** [comment]
If you want to retrieve, you currently would want to do the following:

``` ruby
banks = client.banks.all(id: 123)
banks.first # banks should be an APIList with just 1 bank in it, so you can call banks.first to get it.
```

I didn't make this its own retrieve method (at least for now) because the endpoint currently returns an array of banks, even if an id is provided, so it would be a little odd for a retrieve method. We will likely look into adding that in a bit.
