### ISSUE TITLE
Creating a deposit successfully returns a Deposit with all null attributes

### ISSUE THREAD

**Issue by javierjulio** [synapsepayments/synapse_pay-ruby#7]
Working in sandbox mode, I tested creating another deposit today and noticed that the Deposit object I received, all its properties were had null values but the deposit was created successfully. It shows up in that users' Synapse Dashboard too (I was testing our user update password API to see if I could try logging into their dashboard to verify data, rather than just use the API all the time).

This is the setup I followed:

``` ruby
client = SynapsePay::User.create({
  :email => "jonsmith@example.com",
  :fullname => "Jon Smith",
  :ip_address => "11.111.11.11",
  :phonenumber => "123456789",
  :force_create => "no"
})

bank = client.banks.add({
  :fullname => "Jon Smith",
  :account_num => "1111111111",
  :routing_num => "121000358",
  :nickname => "Example bank account",
  :account_type => "1",
  :account_class => "1"
})

bank_id = client.banks.all.first.id
deposits = client.deposits.micro({
  :bank_id => bank_id,
  :amount1 => "0.07",
  :amount2 => "0.25"
})
```

I had done the above yesterday so today I just logged in as the user through the API in the IRB console. Once I created a deposit:

``` ruby
deposit = client.deposits.create({
  :bank_id => bank_id,
  :amount => "500"
})
```

After the request completes successfully, the response should be a populated Deposit object but instead this is what I get from the deposit variable set in the previous example:

``` ruby
=> #<SynapsePay::Deposit:0x3fccda47d858> Attributes: {
  "amount": null,
  "bank": null,
  "date_created": null,
  "id": null,
  "resource_uri": null,
  "status": null,
  "status_url": null,
  "user_id": null
}
```

**Comment by joncalhoun** [comment]
I believe this was a typo - we were grabbing the json["deposits"] for the singular deposit on a create.

**Comment by javierjulio** [comment]
😞 I feel like this and other issues could have been caught with tests. Don't have the code in front of me but remember seeing tests. Would you be open to pull requests for more? Prefer tests with sandbox access or with just fixtures?

**Comment by joncalhoun** [comment]
Functional tests are coming, but they weren't in the initial release because we opted to share the libraries before we finished them. 

I appreciate the offer for a PR, but I am guessing this is an area where it might be more practical for us to write something that may not be explicitly part of the gem since the tests would then be reliant on sandbox credentials, and are likely going to be very similar across all 4 libraries. Thanks though :smile:

**Comment by javierjulio** [comment]
@joncalhoun great thanks! Yes that's why I offered first because I figured that you would rather keep it consistent across the libraries.
