### ISSUE TITLE
The resource_uri is null in several responses

### ISSUE THREAD

**Issue by javierjulio** [synapsepayments/synapse_pay-ruby#8]
Any object I request seems to have `resource_uri` set to `null`. I'm in sandbox mode. I'm not sure if this is expected but would be nice to be consistent with the responses in the API docs. I outputted the return JSON so it seems the null value is returned from Synapse Pay rather than an issue with the gem but wanted to log somewhere what I found if it helps.

**Comment by sankaet** [comment]
javierjulio -- yes that is the expected response. resource_uri will be null, we have done this because of some confusion it was causing amongst developers. We will update the responses in the docs to reflect this
